# Generated by Django 4.1.5 on 2023-01-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=20)),
                ("grade", models.IntegerField(default=0)),
                ("time_lesson", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("education", models.CharField(blank=True, max_length=20)),
                ("work_experience", models.IntegerField(blank=True)),
                (
                    "amount_courses",
                    models.IntegerField(
                        default=0, verbose_name="amount of courses conducted"
                    ),
                ),
            ],
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "amount_courses",
                    models.IntegerField(
                        default=0, verbose_name="amount of courses attended"
                    ),
                ),
                ("courses", models.ManyToManyField(to="school.course")),
            ],
            options={"verbose_name": "Student", "verbose_name_plural": "Students",},
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="school.teacher"
            ),
        ),
    ]
