# Generated by Django 4.1.5 on 2023-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_course_options_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount_places",
            field=models.IntegerField(default=5, verbose_name="ўсяго месц"),
        ),
        migrations.AddField(
            model_name="course",
            name="amount_studens",
            field=models.IntegerField(
                default=0, verbose_name="колькасць вучаняў зараз"
            ),
        ),
    ]
