# Generated by Django 4.1.5 on 2023-01-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_course_amount_places_course_amount_studens"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="назва")),
                ("content", models.TextField(blank=True, verbose_name="тэкст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="створана"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="зменены"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="site_pictures/%Y/%m/%d",
                        verbose_name="фота",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="апублікавана"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="is_full",
            field=models.BooleanField(default=False, verbose_name="запоўнены"),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="пошта"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="пошта"),
        ),
    ]
