# Generated by Django 4.1.5 on 2023-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_blog_course_is_full_student_email_teacher_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="day_week",
            field=models.CharField(
                choices=[
                    ("monday", "Понедельник"),
                    ("tuesday ", "Вторник"),
                    ("wednesday ", "Среда"),
                    ("thursday ", "Четверг"),
                    ("friday ", "Пятница"),
                    ("saturday  ", "Суббота"),
                    ("sunday  ", "воскресенье"),
                ],
                default="monday",
                max_length=10,
            ),
        ),
    ]
