# Generated by Django 4.1.5 on 2023-01-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course_day_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AddField(
            model_name='student',
            name='tg_id',
            field=models.IntegerField(default=0, verbose_name='id в телеге'),
        ),
    ]
